<div id="dateForm"><?= $this->form; ?></div>
<?php if (is_array($this->blockingReport)): ?>
<?php if (count($this->blockingReport) > 0): ?>
    <?php $summa = 0 ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>ID лицевого счета</th>
            <th>Время начала</th>
            <th>Время окончания</th>
            <th>Что заблокировано</th>
            <th>Тип блокировки</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->blockingReport as $id => $report): ?>
        <tr>
            <td><?= $report['account_id']?></td>
            <td><?= $report['start_date']?></td>
            <td><?= $report['expire_date']?></td>
            <td><?= $report['what_blocked']?></td>
            <td><?= $report['block_type'];?></td>
        </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php else : ?>
        <?= $this->bootAlert(array('success' => 'За заданный период блокировок не было')) ?>
    <?php endif; ?>
<?php else : ?>
    <?= $this->bootAlert(array('info' => 'Выберите период для построения отчёта')) ?>
<?php endif; ?>

<?= $this->cacheInfo($this->cacheData) ?>