<div class="well well-sm"><strong><?= $this->userData['full_name'] ?></strong>
    <small><a href="/user/edit-user" title="Редактировать"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a></small>
</div>
<table class="table table-striped">
    <tr>
        <td>Основной лицевой счёт:</td>
        <td><?= $this->userData['basic_account'] ?> </td>
    </tr>
    <tr>
        <td>Логин:</td>
        <td><?= $this->userData['login'] ?></td>
    </tr>
    <tr>
        <td>Адрес:</td>
        <td><?= $this->userData['actual_address'] ?></td>
    </tr>
    <tr>
        <td>Дата подключения:</td>
        <td><?= $this->userData['create_date'] ?></td>
    </tr>
    <tr>
        <td>Домашний телефон:</td>
        <td><?= $this->userData['home_telephone'] ?></td>
    </tr>
    <tr>
        <td>Мобильный телефон:</td>
        <td><?= $this->userData['mobile_telephone'] ?></td>
    </tr>
    <tr>
        <td>Паспортные данные:</td>
        <td><?= $this->userData['passport'] ?></td>
    </tr>
</table>
<?php if ($this->tarrifs): ?>
    <div class="bs-callout bs-callout-info"><h4>Тарифы</h4></div>
    <?php
    $promised_payments = 1;
    $voluntary_block = 2;
    // $funds_flow = 4;
    $change_tariff = 8;
    ?>
    <?php foreach ($this->tarrifs as $account => $tarrifs): ?>
        <span class="label label-primary">Лицевой счет <?= $account ?></span>

        <?php if (count($tarrifs) > 0) : ?>
            <?php if ($this->additional & $promised_payments): ?>
                <a class="btn btn-default btn-xs" role="button" href="/user/promise-payment/aid/<?= $account ?>">Обещанный платёж</a>
            <?php endif; ?>

            <?php if ($this->additional & $voluntary_block): ?>
                <a class="btn btn-default btn-xs" role="button" href="/user/block/aid/<?= $account ?>">Добровольная блокировка</a>
            <?php endif; ?>
        <?php endif; ?>


        <?php if (count($tarrifs) > 0) : ?>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Название тарифа</th>
                    <th>Следующий ТП</th>
                    <th>Начало расчётного периода</th>
                    <th>Конец расчетного периода</th>
                    <?php if ($this->additional & $change_tariff): ?>
                        <th></th>
                    <?php endif; ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($tarrifs as $tarrif): ?>
                    <tr>
                        <td><strong><?= $tarrif['cyr_tp_name'] ?></strong>
                            <?php if (strlen($tarrif['cyr_tp_descr']) > 0): ?>
                                <br>Описание: <small><?= $tarrif['cyr_tp_descr'] ?></small>
                            <?php endif; ?>
                        </td>
                        <td><strong><?= $tarrif['next_tp_name'] ?></strong>
                            <?php if (strlen($tarrif['next_tp_descr']) > 0): ?>
                                <br>Описание: <small><?= $tarrif['next_tp_descr'] ?></small>
                            <?php endif; ?>
                        </td>
                        <td><?= $tarrif['ap_id_start'] ?> </td>
                        <td><?= $tarrif['ap_id_end'] ?> </td>
                        <?php if ($this->additional & $change_tariff): ?>
                            <td><a class="btn btn-default" role="button" href="<?= $tarrif['link'] ?>">Изменить тариф</a></td>
                        <?php endif; ?>

                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <?= $this->bootAlert(array('info' => 'Нет подключенных тарифов')) ?>
        <?php endif; ?>

        <table class="table table-striped">
            <tr>
                <td class="span3">Баланс</td>
                <td><?= $this->balance($this->accounts[$account]['balance'], $this->accounts[$account]['credit'], $this->currencyName) ?></td>
            </tr>
            <tr>
                <td class="span3">Статус интернета</td>
                <td>
                    <?php $style = $this->accounts[$account]['int_status'] ? 'success' : 'danger' ?>

                    <span class="label label-<?= $style ?>">
                    <?= Urfa_Resolve::resolveIntStatus($this->accounts[$account]['int_status']) ?>
                </span> &nbsp;
                    <a class="btn btn-default btn-xs" role="button"
                       href="/user/change-status/int_status/<?= (int)!$this->accounts[$account]['int_status'] ?>/aid/<?= $account ?>">
                        <?= Urfa_Resolve::resolveIntStatusForAccount($this->accounts[$account]['int_status']) ?>
                    </a>
                </td>
            </tr>
            <tr>
                <td class="span3">Состояние блокировки</td>
                <td>
                    <?php switch ($this->accounts[$account]['block_status']) {
                        case 4294967295:
                        case -1: //none
                            $style = 'success';
                            break;
                        default: //block
                            $style = 'danger';
                    } ?>
                    <span class="label label-<?= $style ?>">
                    <?= DRG_Urfautils::blockedStatus($this->accounts[$account]['block_status']) ?>
                </span>
                </td>
            </tr>

            <tr>
                <td class="span3">НДС</td>
                <td><?= $this->accounts[$account]['vat_rate'] ?></td>
            </tr>
        </table>

    <?php endforeach; ?>
<?php endif; ?>

<?php if ($this->services): ?>
    <div class="bs-callout bs-callout-info"><h4>Услуги</h4></div>
    <table class="table table-striped">
    <?php if (count($this->services) > 0) : ?>
        <thead>
        <tr>
            <th>Тип услуги</th>
            <th>Имя услуги</th>
            <th>Имя тарифа</th>
            <th>Начало расч. периода</th>
            <th>Конец расч. периода</th>
            <th>Абон. плата</th>
            <th>Списано</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->services as $slinks): ?>
            <tr>
                <td><?= $slinks['service_type_name'] ?></td>
                <td><?= $slinks['link'] ?> </td>
                <td><?= $slinks['tariff_name'] ?> </td>
                <td><?= $slinks['discount_period_start'] ?> </td>
                <td><?= $slinks['discount_period_end'] ?> </td>
                <td><?= $slinks['cost'] ?> </td>
                <td><?= $slinks['discounted_in_curr_period'] ?> </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
    <?php else: ?>
        <?= $this->bootAlert(array('info' => 'Нет подключенных услуг')) ?>
    <?php endif; ?>
<?php endif; ?>


<?php if ($this->turbo): ?>
    <div class="bs-callout bs-callout-info"><h4>Турбо-режим</h4></div>
    <table class="table table-striped">
    <?php if (count($this->turbo) > 0) : ?>
        <thead>
        <tr>
            <th>Имя</th>
            <th>Действие</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->turbo as $slinks): ?>
            <tr>
                <td><?= $slinks['name'] ?></td>
                <?php if ($slinks['active']): ?>
                    <td><a href="/user/service/slink/<?= $slinks['id'] ?>">Включен</a></td>
                <?php else: ?>
                    <td><a href="/user/service/slink/<?= $slinks['id'] ?>">Включить</a></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
<?= $this->cacheInfo($this->cacheData) ?>