<div id="dateForm"><?= $this->form; ?></div>
<?php if (is_array($this->userPaymentData)): ?>
<?php if (count($this->userPaymentData) > 0): ?>
    <?php $summa = 0 ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Аккаунт</th>
            <th>Дата платежа</th>
            <th>Дата внесения</th>
            <th>Сумма</th>
            <th>комментарий</th>
            <th>Метод платежа</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->userPaymentData as $j): ?>
                <?php foreach ($j as $userPayment): ?>
                    <tr>
                        <td><?= $userPayment['account']?></td>
                        <td><?= $userPayment['actual_payment_date']?></td>
                        <td><?= $userPayment['date_of_payment']?></td>
                        <td><?= $userPayment['volume']; $summa += $userPayment['volume']?> <?= $this->currencyName?></td>
                        <td><?= $userPayment['comment']?></td>
                        <td><?= $userPayment['payment_method']?></td>
                    </tr>
                <?php endforeach;?>
            <?php endforeach;?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3">
                <b>Итого:</b>
            </td>
            <td><b><?=$summa?></b> <?= $this->currencyName?></td>
            <td colspan="2"></td>
        </tr>
        </tfoot>
    </table>
    <?php else : ?>
        <?= $this->bootAlert(array('success' => 'Платежи отсутствуют')) ?>
    <?php endif; ?>

    <?php if (is_array($this->burntPaymentData)): ?>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Дата первого платежа</th>
                <th>Дата последнего платежа</th>
                <th>Время сгорания</th>
                <th>Сумма</th>
                <th>Списано</th>
            </tr>
            </thead>
            <tbody>
                    <tr>
                        <td><?= $this->burntPaymentData['first_payment_date']?></td>
                        <td><?= $this->burntPaymentData['last_payment_date']?></td>
                        <td><?= $this->burntPaymentData['time_to_burn']?></td>
                        <td><?= $this->burntPaymentData['amount'];?></td>
                        <td><?= $this->burntPaymentData['discounted']?></td>
                    </tr>
            </tbody>
        </table>
    <?php endif; ?>


<?php else : ?>
    <?= $this->bootAlert(array('info' => 'Выберите период для построения отчёта')) ?>
<?php endif; ?>

<?= $this->cacheInfo($this->cacheData) ?>