<?php if (is_array($this->services)): ?>
    <?php if (isset($this->services['service'])): ?>
        <div class="bs-callout bs-callout-info"><h4>Услуга</h4></div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Тип услуги</th>
                <th>Имя услуги</th>
                <th>Абон. плата</th>
                <th>Списано</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td><?= $this->services['service']['type_name'] ?></td>
                <td><?= $this->services['service']['name'] ?></td>
                <td><?= $this->services['service']['cost_in_period'] ?> </td>
                <td><?= $this->services['service']['discounted_in_curr_period'] ?></td>
            </tr>
            </tbody>
        </table>
        <?php if ($this->services['service']['type'] == 6): ?>
            <?php if (isset($this->services['telephones'])): ?>
                <div class="bs-callout bs-callout-info"><h4>Телефоны</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="25%">Номер</th>
                        <th width="25%">Логин</th>
                        <th width="25%">Разрешенные CID</th>
                        <th width="25%">Пароль</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->services['telephones'] as $id => $acc): ?>
                        <tr>
                            <td><?= $acc['number'] ?></td>
                            <td><?= $acc['login'] ?></td>
                            <td><?= $acc['allowed_cid'] ?></td>
                            <td><?= $acc['link'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        <?php elseif ($this->services['service']['type'] == 3): ?>
            <?php if (isset($this->services['downloaded']) && count($this->services['downloaded'])): ?>
                <div class="bs-callout bs-callout-info"><h4>Скачано в текущем учетном периоде</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="70%">Класс трафика</th>
                        <th>Скачано в текущем учетном периоде</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $flag = false; ?>
                    <?php foreach ($this->services['downloaded'] as $service): ?>
                        <?php if ($service['mbytes'] > 0): ?>
                            <?php $flag = true; ?>
                            <tr>
                                <td><?= $service['tclass'] ?></td>
                                <td><?= $service['mbytes'] ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if (!$flag): ?>
                        <tr>
                            <td colspan="2">
                                <i class="icon-info-sign"></i> Нет использованного трафика
                            </td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php if (isset($this->services['prepaid']) && count($this->services['prepaid'])): ?>
                <div class="bs-callout bs-callout-info"><h4>Предоплачено</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="70%">Класс трафика</th>
                        <th>Предоплачено, МБ</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $flag = false; ?>
                    <?php foreach ($this->services['prepaid'] as $service): ?>

                        <?php if ($service['mbytes'] > 0): ?>
                            <?php $flag = true; ?>
                            <tr>
                                <td><?= $service['tclass'] ?></td>
                                <td><?= $service['mbytes'] ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if (!$flag): ?>
                        <tr>
                            <td colspan="2">
                                <i class="icon-info-sign"></i> Нет предоплаченного трафика
                            </td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php if (isset($this->services['transfered']) && count($this->services['transfered'])): ?>
                <div class="bs-callout bs-callout-info"><h4>Перенесено предоплаченного с прошлого учетного периода</h4>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="70%">Класс трафика</th>
                        <th>Перенесено, МБ</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $flag = false; ?>
                    <?php foreach ($this->services['transfered'] as $service): ?>
                        <?php if ($service['mbytes'] > 0): ?>
                            <?php $flag = true; ?>
                            <tr>
                                <td><?= $service['tclass'] ?></td>
                                <td><?= $service['mbytes'] ?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if (!$flag): ?>
                        <tr>
                            <td colspan="2">
                                <i class="icon-info-sign"></i> Нет перенесённого трафика
                            </td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php if (isset($this->services['borders']) && count($this->services['borders'])): ?>
                <div class="bs-callout bs-callout-info"><h4>Границы тарификации</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="50%">Класс трафика</th>
                        <th width="20%">Граница, МБ</th>
                        <th width="30%">Стоимость за МБ</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->services['borders'] as $service): ?>
                        <tr>
                            <td><?= $service['tclass'] ?></td>
                            <td><?= $service['mbytes'] ?></td>
                            <td><?= $service['cost'] ?> <?= $this->currencyName ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php if (isset($this->services['ip_groups'])): ?>
                <div class="bs-callout bs-callout-info"><h4>IP-группы</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th width="25%">IP</th>
                        <th width="25%">Маска</th>
                        <th width="25%">Логин</th>
                        <th width="25%">Пароль</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->services['ip_groups'] as $service): ?>
                        <tr>
                            <td><?= $service['ip'] ?></td>
                            <td><?= $service['mask'] ?></td>
                            <td><?= $service['login'] ?></td>
                            <td><?php if (!empty($service['login'])) {
                                    echo $service['link'];
                                } ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>


            <?php if (isset($this->services['shaping']) && $this->services['shaping']['show_shaping'] == true): ?>
                <div class="bs-callout bs-callout-info"><h4>Скорость</h4></div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Входящий канал</th>
                        <th>Исходящий канал</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $this->services['shaping']['incoming_rate'] ?></td>
                        <td><?= $this->services['shaping']['outgoing_rate'] ?></td>
                    </tr>
                    </tbody>
                </table>


                <?php if ($this->services['shaping']['turbo_mode_available'] == true): ?>
                    <?php if ($this->services['shaping']['turbo_mode_start'] != 0): ?>
                        <div class="bs-callout bs-callout-info"><h4>Турбо-режим</h4></div>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Имя</th>
                                <th>Скорость</th>
                                <th>Цена</th>
                                <th>Действует</th>
                            </tr>
                            </thead>
                            <?php
                            $name = '';
                            if (count($this->services['turbo'])) {
                                for ($i = 0; $i < count($this->services['turbo']); $i++) {
                                    if ($this->services['turbo'][$i]['id'] == $this->services['shaping']['turbomode_settings_id']) {
                                        $name = $this->services['turbo'][$i]['name'];
                                        break;
                                    }
                                }
                            }

                            $endAt = '';
                            if ($this->shaping['incoming_consumption_left'] == 0 &&
                                $this->shaping['outgoing_consumption_left'] == 0
                            ) {
                                $endAt = 'до '.Urfa_Resolve::getDateFromTimestamp($this->services['shaping']['turbo_mode_end']);
                            } else {
                                $endAt = Urfa_Resolve::resolveLimit($this->services['shaping']['incoming_consumption_left'], 1024).' / '.
                                    Urfa_Resolve::resolveLimit($this->services['shaping']['outgoing_consumption_left'], 1024);
                            }
                            ?>

                            <tbody>
                            <tr>
                                <td><?php echo $name ?></td>
                                <td><?php echo Urfa_Resolve::resolveRate($this->services['shaping']['incoming_rate']).' / '.
                                        Urfa_Resolve::resolveRate($this->services['shaping']['outgoing_rate']) ?>
                                </td>
                                <td><?= Urfa_Resolve::getDateFromTimestamp($this->services['shaping']['turbo_mode_start']) ?></td>
                                <td><?php echo $endAt ?></td>

                            </tr>
                            </tbody>
                        </table>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if (isset($this->services['turbo'])): ?>
                    <div class="bs-callout bs-callout-info"><h4>Доступные турбо-режимы</h4></div>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Скорость</th>
                            <th>Цена</th>
                            <th>Действует</th>
                            <?php if ($this->services['shaping']['turbo_mode_start'] == 0) : ?>
                                <th>Действие</th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->services['turbo'] as $turbo) : ?>

                            <?php
                            $endAt = '';
                            if (isset($turbo['duration'])) {
                                $endAt = Urfa_Resolve::getTimeFromSec($turbo['duration']);
                            } else {
                                $endAt = 'при достижении лимитов '.
                                    Urfa_Resolve::resolveLimit($turbo['incoming_limit'], 1024).' / '.
                                    Urfa_Resolve::resolveLimit($turbo['outgoing_limit'], 1024);
                            }
                            ?>

                            <tr>
                                <td><?= $turbo['name'] ?></td>
                                <td><?= Urfa_Resolve::resolveRate($turbo['incoming_rate']) ?>/<?= Urfa_Resolve::resolveRate($turbo['outgoing_rate']) ?></td>

                                <td><?= $turbo['cost'] ?></td>
                                <td><?= $endAt ?></td>
                                <?php if ($this->services['shaping']['turbo_mode_start'] == 0) : ?>
                                    <td><a href="/user/turbo-mode/slink_id/<?= $this->slink ?>/settings_id/<?= $turbo['id'] ?>">Включить</a></td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
            <?php endif; ?>

        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

<?= $this->cacheInfo($this->cacheData) ?>
